config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :instructors
  devise_for :admins

  resources :students do
    collection do
      get :auth
      get :schedule
      get :pay_online
      get :finish_payment
    end
  end

  resources :courses, only: [:index, :show]
  resources :lessons, only: [:index, :show]

  resources :course_students, only: [:create]
  resources :lesson_students, only: [:create]

  post 'create_invoices' => 'invoices#mass_create'

  get 'track-visit' => 'visits#track_visit'
  resources :payments, only: [:create]

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'prices' => 'home#prices'
  get 'gracias' => 'home#gracias'
  get 'como-matricular' => 'home#como-matricular'
  get 'import' => 'home#import'
  get 'contrataciones' => 'home#contrataciones'
  get 'contrataciones/gracias' => 'home#gracias'

  get 'select-schedule', to: 'promo#select_schedule'
  get 'thank-you', to: 'promo#thank_you'

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable,
         :validatable

  enum status: { active: 1, inactive: 2 }

  belongs_to :district
  belongs_to :branch

  has_many :subscriptions
  has_many :active_subscriptions, -> { where('finished_at IS NULL OR finished_at >= CURRENT_TIMESTAMP') }, class_name: 'Subscription'
  has_many :courses_students, class_name: 'CourseStudent', dependent: :destroy

  has_many :courses, through: :courses_students
  has_many :dance_courses, -> { where(kind: 1) }, class_name: 'Course',
           through: :courses_students, source: :course

  has_many :lessons_students, class_name: 'LessonStudent', dependent: :destroy
  has_many :lessons, through: :lessons_students
  has_many :invoices
  has_many :payments
  has_many :visits

  validates_presence_of :first_name, :last_name, :second_last_name, :id_number, :birthdate, :phone
  validates_uniqueness_of :id_number
  validates_length_of :lessons, maximum: 4

  scope :with_pending_invoices, -> { joins(:invoices).where(invoices: { payed: false }) }
  scope :active_students, -> { active }
  scope :inactive_students, -> { inactive }

  include PgSearch
  pg_search_scope :search_by_main_fields, against: [:first_name, :last_name]

  def self.process_all_statuses
    Student.all.each { |s| s.process_status! }
  end

  def process_status!
    if student_is_active?
      update!(status: 'active')
    else
      update!(status: 'inactive')
    end
  end

  def full_name
    "#{first_name} #{last_name} #{second_last_name}"
  end

  def label
    "#{id_number} #{full_name}"
  end

  def address
    "#{district.canton.province}, #{district.canton}, #{district}"
  end

  def create_invoice!
    if active_subscriptions.any? && invoices.where('created_at >= ? ', Date.today.beginning_of_month).empty?
      subscription = active_subscriptions.last

      invoice = invoices.build

      # if dance_courses.any?
      #   prev_invoices_for_that_course = invoices.where('created_at < ?', Date.today).find_all do |i|
      #     i.course_id == dance_courses.first.id
      #   end
      # else
      #   prev_invoices_for_that_course = []
      # end
      # if prev_invoices_for_that_course.empty?
      #   invoice.items.build(name: 'Tuition', price: subscription.tuition)
      # end

      if (Date.today - Date.today.beginning_of_month).days > 10.days
        invoice.items.build(name: 'Plan de danza',
                            price: subscription.price)
      else
        invoice.items.build(name: 'Plan de danza',
                            price: subscription.price,
                            price_with_discount: subscription.price_with_discount)
      end

      invoice.save!

      invoice
    end
  end

  # def check_status!
  #   if invoices.where(payed: false).empty? && active_subscriptions.any?
  #     update!(status: :active)
  #   else
  #     update!(status: :inactive)
  #   end
  # end

  def student_is_active?
    invoices.where(payed: false).empty? && active_subscriptions.any?
  end
  alias_method :student_is_active, :student_is_active?

  def student_is_inactive?
    !student_is_active?
  end

  def dance_courses_for_next_semester
    current_year = CourseStudent::CURRENT_SEMESTER[:year]
    current_semester = CourseStudent::CURRENT_SEMESTER[:semester]
    prev_courses = courses_students.find_all do |cs|
      (cs.year == current_year && cs.semester < current_semester) ||
        (cs.year < current_year)
    end
    prev_courses.map!(&:course)

    next_courses = Course.where(kind: 1).all.find_all do |c|
      prev_courses.include?(c.parent)
    end

    if next_courses.empty?
      [Course.base]
    else
      next_courses
    end
  end

  def last_visit
    visits.order(timestamp: :desc).first
  end
end

app/controllers/export/students_controller.rb
class Export::StudentsController < ApplicationController
  load_resource

  def index
    # if admin_signed_in?
      render json: Student.all
    # else
    #   render root_path
    # end
  end
end

app/controllers/students/confirmations_controller.rb
class Student::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
class Student::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
class Student::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
class Students::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def create
    password = Devise.friendly_token.first(8)

    p = sign_up_params
    p['password'] = password

    build_resource(p)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end

    # super ^^^

    if resource.persisted?
      if resource.beginner?
        ConfirmRegistrationJob.perform_later(resource, password, beginner: true)
        Course.base.students << resource

        set_flash_message!(:notice, 'signed_up_and_basic_course')
      else
        ConfirmRegistrationJob.perform_later(resource, password)
        NotifyAdminJob.perform_later(resource)

        flash[:notice] = nil
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.
      permit(:sign_up,
             keys: [:first_name, :last_name, :second_last_name, :id_number, :birthdate, :phone,
                    :branch_id, :beginner])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.
      permit(:account_update,
             keys: [:first_name, :last_name, :second_last_name, :id_number, :birthdate, :phone,
                    :branch_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_in_path_for(resource)
    flash[:alert] = nil

    select_schedule_path
  end
end

app/controllers/students/sessions_controller.rb
class Student::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
class Student::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def auth
  end

  def show

  end

  def schedule
    @student = current_student

    if params[:new_course]
      # @student.courses << Course.find(params[:new_course])
      @student.courses_students.create(
        CourseStudent::CURRENT_SEMESTER.merge({ course_id: params[:new_course] })
      )
    end

    if params[:lesson_ids].try(:any?)
      @student.lesson_ids = params[:lesson_ids]

      # ConfirmScheduleEnrollmentJob.perform_later(@student)
      # NotifyAdminJob.perform_later(@student)
    end

    @days = {}
    I18n.t('date.day_names').each_with_index do |name, index|
      i = (0 == index ? 7 : index)
      @days[i] = name
    end

    @lessons = {}
    current_student.courses.each do |course|
      lessons_by_week = course.lessons.where(branch_id: current_student.branch_id).group_by { |l| l[:day_of_week] }
      (1..7).each do |day_number|
        unless lessons_by_week[day_number].present?
          lessons_by_week[day_number] = []
        end
      end

      @lessons[course.id] = lessons_by_week
    end
  end

  # Start process of payment
  def pay_online
    authenticate_student!
  end

  # Finish process of payment (callback url)
  def finish_payment
    if params[:sum].present? && params[:student_id].present? && params[:invoice_id].present?
      Student.find(params[:student_id]).payments.create!(invoice_id: params[:invoice_id],
                                                         sum: params[:sum],
                                                         accepted: true,
                                                         method: :card)
      render plain: 'Payment accepted'
    else
      render plain: 'No payment found'
    end
  end
end

app/views/students/_add_new_course.html.erb
<%= form_tag schedule_students_path, method: :get do %>
  <div class="form-group">
    <label><%= t('helpers.student.select_course') %></label>

    <select name="new_course" class="form-control">
      <% @student.dance_courses_for_next_semester.each do |course| %>
        <option value="<%= course.id %>"><%= course.name %></option>
      <% end %>
    </select>
  </div>

  <button class="btn btn-primary"><%= t('helpers.student.apply_for_new_course') %></button>
<% end %>

app/views/students/_invoices.html.erb
<h3>Invoices</h3>

<table class="table">
  <thead>
  <tr>
    <th>#</th>
    <th>Payed?</th>
    <th>Date</th>
    <th>Sum</th>
  </tr>
  </thead>
  <tbody>
  <% current_student.invoices.each do |invoice| %>
    <tr class="<%= 'danger' unless invoice.payed? %>">
      <th><%= invoice.id %></th>
      <td>
        <% if invoice.payed? %>
          <i class="fa fa-check" style="font-size: 2em; margin-top: -0.2em;"></i>
        <% else %>
          <%= form_for invoice.payments.build do |f| %>
            <%= f.hidden_field :student_id, value: current_student.id %>
            <%= f.hidden_field :invoice_id, value: invoice.id %>
            <%= f.hidden_field :sum, value: invoice.total %>

            <%= f.label :comment, 'Confirmation number' %>
            <%= f.text_field :comment %>

            <%= f.submit 'Add' %>
          <% end %>
        <% end %>
      </td>
      <td><%= l(invoice.created_at.to_date) %></td>
      <td><%= number_to_currency(invoice.total) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/_payments.html.erb
<h3>Payments</h3>

<table class="table">
  <thead>
  <tr>
    <th>#</th>
    <th>Date</th>
    <th>Sum</th>
    <th>Invoice</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% current_student.payments.each do |payment| %>
    <tr class="<%= 'text-muted' unless payment.accepted? %>">
      <th><%= payment.id %></th>
      <td><%= l(payment.created_at.to_date) %></td>
      <td><%= number_to_currency(payment.sum) %></td>
      <td>
        <% if payment.invoice.present? %>
          #<%= payment.invoice.id %>, <%= l(payment.invoice.created_at.to_date) %>
        <% end %>
      </td>
      <td>
        <% if payment.accepted? %>
          Accepted.
        <% else %>
          Checking...
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/auth.html.erb
<div class="row text-center">
  <div class="cols-xs-12">
    <h2>¿Ya te has registrado en nuestra página?</h2>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-xs-6 col-md-3 text-center col-md-offset-3">
    <%= link_to 'Sí, me he registrado antes', new_student_session_path, class: "btn btn-primary btn-lg" %>
  </div>
  <div class="col-xs-6 col-md-3 text-center">
    <%= link_to 'No, nunca me he registrado', new_student_registration_path, class: "btn btn-danger btn-lg" %>
  </div>
</div>
<br/>
<div class="row text-center">
  <div class="col-xs-12">
    <p>Si ya te has registrado antes, te eviaremos un password a tu correo</p>
  </div>
</div>

app/views/students/pay_online.html.erb
<form method="get" action="http://google.com">
  <input type="hidden" name="q" value="accept payments over the Internet">

  <div class="form-group">
    <label for="sum">Sum</label>
    <input type="number" class="form-control" id="sum">
  </div>

  <button type="submit" class="btn btn-default">Pay online</button>
</form>

app/views/students/schedule.html.erb
<h2>
  <%= t('helpers.student.select_your_schedule') %>
</h2>

<p>Seleccioná tus cursos para este semestre</p>

<%= render partial: 'add_new_course' %>

<hr>

<p><%= t('helpers.student.selec_max_description') %></p>

<%= form_tag schedule_students_path, method: :get do %>
  <% CourseStudent::ACTUAL_SEMESTERS.each do |date| %>
    <% @student.courses_students.each do |course_student| %>
      <% next unless (date[:year] == course_student.year && date[:semester] == course_student.semester) %>
      <% course = course_student.course %>

      <p>
        <%= t('helpers.student.you_are_enrolled_to_course', course_name: course.name) %>
        (<%= date[:year] %>, <%= 1 == date[:semester] ? 'spring' : 'autumn' %>)
      </p>
      <br>

      <p class="select_max_3_lessons" style="color: red; display: none;">
        <%= t('helpers.student.select_max_3_lessons') %>
      </p>
      <table class="table calendar">
        <tr>
          <% @days.sort.each do |_, v| %>
            <th><%= v.capitalize %></th>
          <% end %>
        </tr>
        <tr>
          <% @lessons[course.id].sort.to_h.each do |_, lessons| %>
            <td>
              <ul class="list-unstyled">
                <% lessons.sort_by(&:time_interval).each do |lesson| %>
                  <% checked = @student.lessons.include?(lesson) %>
                  <li style="margin-bottom: 10px;">
                    <button class="btn <%= checked ? 'btn-primary' : 'btn-default' %>"
                            data-lesson="<%= lesson.id %>">
                      <%= lesson.time_interval %>
                    </button>

                    <input type="checkbox" name="lesson_ids[]" id="lesson_<%= lesson.id %>"
                           value="<%= lesson.id %>" class="hidden" <%= 'checked' if checked %>>
                  </li>
                <% end %>
              </ul>
            </td>
          <% end %>
        </tr>
      </table>

    <% end %>
  <% end %>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      $('.calendar button').click(function(event) {
        if ($(this).hasClass('btn-primary')) {
          $('#lesson_' + $(this).attr('data-lesson')).attr('checked', false);
          $(this).toggleClass('btn-default');
          $(this).toggleClass('btn-primary');
          if ($(this).parents('.calendar').find('.btn-primary').length < 3) {
            $(this).parents('.calendar').prev('.select_max_3_lessons').hide();
          }
        } else {
          if ($(this).parents('.calendar').find('.btn-primary').length < 3) {
            $('#lesson_' + $(this).attr('data-lesson')).attr('checked', true);
            $(this).toggleClass('btn-default');
            $(this).toggleClass('btn-primary');
          } else {
            $(this).parents('.calendar').prev('.select_max_3_lessons').show();
          }
        }
        event.preventDefault();
      });
    });
  </script>

  <button id="apply_for_lesson" class="btn btn-primary">
    <%= t('helpers.student.apply_for_lesson') %>
  </button>
<% end %>

app/views/students/show.html.erb
<h2><%= current_student.full_name %></h2>

<br>

<%= link_to 'Edit profile', edit_student_registration_path, class: 'btn btn-success' %>

<hr>

<%= render 'invoices' if current_student.invoices.any? %>

<%= render 'payments' if current_student.payments.any? %>