config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :instructors
  devise_for :admins

  resources :students do
    collection do
      get :auth
      get :schedule
      get :pay_online
      get :finish_payment
    end
  end

  resources :courses, only: [:index, :show]
  resources :lessons, only: [:index, :show]

  resources :course_students, only: [:create]
  resources :lesson_students, only: [:create]

  post 'create_invoices' => 'invoices#mass_create'

  get 'track-visit' => 'visits#track_visit'
  resources :payments, only: [:create]

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'prices' => 'home#prices'
  get 'gracias' => 'home#gracias'
  get 'como-matricular' => 'home#como-matricular'
  get 'import' => 'home#import'
  get 'contrataciones' => 'home#contrataciones'
  get 'contrataciones/gracias' => 'home#gracias'

  get 'select-schedule', to: 'promo#select_schedule'
  get 'thank-you', to: 'promo#thank_you'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :students
  has_many :branch_instructors, class_name: 'BranchInstructor', dependent: :destroy
  has_many :instructors, through: :branch_instructors
  has_many :lessons

  validates_presence_of :name

  def as_json(options = nil)
    attrs = {
      only: [
        'id',
        'name',
        'created_at',
        'updated_at'
      ]
    }

    super(attrs.merge(options || {}))
  end
end

app/controllers/promo_controller.rb
class PromoController < ApplicationController
  before_action :authenticate_student!, except: [:registration]

  def registration
    if student_signed_in?
      redirect_to select_schedule_path
    else
      redirect_to new_student_registration_path
    end
  end

  def select_schedule
    @student = current_student

    if params[:lesson_ids].try(:any?)
      lessons = Lesson.where(id: params[:lesson_ids])
      @student.lessons.concat(lessons)

      ConfirmScheduleEnrollmentJob.perform_later(@student)
      NotifyAdminJob.perform_later(@student)
    end

    if @student.lessons.any? || !@student.beginner?
      redirect_to thank_you_path
    end

    @days = {}
    I18n.t('date.day_names').each_with_index do |name, index|
      i = (0 == index ? 7 : index)
      @days[i] = name
    end

    @course = Course.base

    @lessons_by_week = @course.lessons.where(branch_id: current_student.branch_id).group_by { |l| l[:day_of_week] }
    (1..7).each do |day_number|
      unless @lessons_by_week[day_number].present?
        @lessons_by_week[day_number] = []
      end
    end

    # start_time = Time.parse('00:00')
    # times = [start_time]
    # 48.times do |n|
    #   times << (start_time + n * 30.minutes)
    # end
    #
    # (1..7).each do |day_number|
    #   lessons = @lessons_by_week[day_number]
    #
    #   lessons_by_time = Hash.new([])
    #   times.each do |t|
    #     lessons.each do |lesson|
    #       if lesson.start_time.utc.strftime('%H%M%S%N') >= t.utc.strftime('%H%M%S%N') &&
    #         lesson.start_time.utc.strftime('%H%M%S%N') < (t + 30.minutes).utc.strftime('%H%M%S%N')
    #
    #         fail '234'
    #         lessons_by_time[t] << lesson
    #       end
    #     end
    #   end
    #
    #   @lessons_by_week[day_number] = lessons_by_time
    # end
  end

  def thank_you
    @student = current_student

    if @student.beginner? && @student.lessons.empty?
      redirect_to select_schedule_path
    end
  end
end

app/views/promo/select_schedule.html.erb
<h2>
  <%= t('helpers.student.select_your_schedule') %>
</h2>
<p><%= t('helpers.student.selec_max_description') %></p>

<p><%= t('helpers.student.you_are_enrolled_to_course', course_name: @course.name) %></p>

<br>

<%= form_tag select_schedule_path, method: :get do %>
  <p id="select_max_3_lessons" style="color: red; display: none;">
    <%= t('helpers.student.select_max_3_lessons') %>
  </p>
  <table id="calendar" class="table">
    <tr>
      <% @days.sort.each do |_, v| %>
        <th><%= v.capitalize %></th>
      <% end %>
    </tr>
    <tr>
      <% @lessons_by_week.sort.to_h.each do |_, lessons| %>
        <td>
          <ul class="list-unstyled">
            <% lessons.sort_by(&:time_interval).each do |lesson| %>
              <li style="margin-bottom: 10px;">
                <button class="btn btn-default" data-lesson="<%= lesson.id %>">
                  <%= lesson.time_interval %>
                </button>

                <input type="checkbox" name="lesson_ids[]" id="lesson_<%= lesson.id %>"
                       value="<%= lesson.id %>" class="hidden">
              </li>
            <% end %>
          </ul>
        </td>
      <% end %>
    </tr>
  </table>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      $('#calendar button').click(function(event) {
        if ($(this).hasClass('btn-primary')) {
          $('#lesson_' + $(this).attr('data-lesson')).attr('checked', false);
          $(this).toggleClass('btn-default');
          $(this).toggleClass('btn-primary');
          if ($('#calendar .btn-primary').length < 3) {
            $('#select_max_3_lessons').hide();
          }
        } else {
          if ($('#calendar .btn-primary').length < 3) {
            $('#lesson_' + $(this).attr('data-lesson')).attr('checked', true);
            $(this).toggleClass('btn-default');
            $(this).toggleClass('btn-primary');
          } else {
            $('#select_max_3_lessons').show();
          }
        }
        event.preventDefault();
      });
    });
  </script>

  <button id="apply_for_lesson" class="btn btn-primary">
    <%= t('helpers.student.apply_for_lesson') %>
  </button>
<% end %>

<br>
<br>

app/views/promo/thank_you.html.erb
<h2>
  <%= t('devise.registrations.thank_you.title') %>
</h2>

<p class="lead"><%= t('devise.registrations.thank_you.text') %></p>

<!--
<% if @student.beginner? %>
  <p><%= t('devise.registrations.student.signed_up_and_basic_course') %></p>
<% else %>
  <p><%= t('devise.registrations.student.signed_up_and_advanced_course') %></p>
<% end %>
-->

<% if student_signed_in? %>
  <br><br>
  <%= link_to t('helpers.student.edit_profile'), edit_registration_path(:student),
              class: 'btn btn-default' %>

  <%= link_to t('devise.sign_out'), destroy_student_session_path,
              method: :delete, class: 'btn btn-danger' %>
<% end %>