config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :instructors
  devise_for :admins

  resources :students do
    collection do
      get :auth
      get :schedule
      get :pay_online
      get :finish_payment
    end
  end

  resources :courses, only: [:index, :show]
  resources :lessons, only: [:index, :show]

  resources :course_students, only: [:create]
  resources :lesson_students, only: [:create]

  post 'create_invoices' => 'invoices#mass_create'

  get 'track-visit' => 'visits#track_visit'
  resources :payments, only: [:create]

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'prices' => 'home#prices'
  get 'gracias' => 'home#gracias'
  get 'como-matricular' => 'home#como-matricular'
  get 'import' => 'home#import'
  get 'contrataciones' => 'home#contrataciones'
  get 'contrataciones/gracias' => 'home#gracias'

  get 'select-schedule', to: 'promo#select_schedule'
  get 'thank-you', to: 'promo#thank_you'

end

app/views/shared/_login.html.erb
<% if student_signed_in? %>
  <%= link_to 'Logout', destroy_student_session_path, method: :delete %>
<% else %>
  <%= link_to 'Login', new_student_session_path %>
<% end %>

app/views/shared/_registration.html.erb
<% if student_signed_in? %>
  <%= link_to 'Edit registration', edit_student_registration_path %>
<% else %>
  <%= link_to 'Register', new_student_registration_path %>
<% end %>