config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :instructors
  devise_for :admins

  resources :students do
    collection do
      get :auth
      get :schedule
      get :pay_online
      get :finish_payment
    end
  end

  resources :courses, only: [:index, :show]
  resources :lessons, only: [:index, :show]

  resources :course_students, only: [:create]
  resources :lesson_students, only: [:create]

  post 'create_invoices' => 'invoices#mass_create'

  get 'track-visit' => 'visits#track_visit'
  resources :payments, only: [:create]

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'prices' => 'home#prices'
  get 'gracias' => 'home#gracias'
  get 'como-matricular' => 'home#como-matricular'
  get 'import' => 'home#import'
  get 'contrataciones' => 'home#contrataciones'
  get 'contrataciones/gracias' => 'home#gracias'

  get 'select-schedule', to: 'promo#select_schedule'
  get 'thank-you', to: 'promo#thank_you'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @slides = Slide.all
    @instructors = Instructor.all
    @testimonials = Testimonial.all
  end

  def prices
    @plans = DancePlan.all.sort_by &:position
  end
end

app/views/home/como-matricular.html.erb
<h1>¿Cómo matricular?</h1>

<p>Matricular es sencillo, simplemente llená este formulario <%= link_to "(click aquí)", auth_students_path %> y escogé tu horario. Luego hacé el depósito en cualquiera de nuestras cuentas bancarias y envíanos el comprobante a info@bellydancecr.com.</p>

<p>Otra de las formas de matricular es visitando la sede luego de haber realizando la reservación del cupo ( pre-matrícula ) y con el correo de confirmación puede recibir la clase de cortesía. Ese mismo día de la visita podés finalizar el proceso de inscripción. </p>
<p>Solo tenés que llegar 15 minutos antes de la clase que elegiste, en la sede que seleccionaste.
Recordá llegar con ropa cómoda y te recomendamos traer un pañito. </p>
<p>Nota: Ni la pre-matrícula, ni la reservación del cupo, ni la clase de cortesía tiene costo alguno. </p>
<p><strong>Te esperamos!</strong></p>

<h2>Cuentas de banco Academia</h2>
<div class="row">
  <div class="col-md-6">
    <h3>Banco Nacional</h3>
    <p><strong>Colones</strong><br/>
    Cuenta BN₡: 100-01-137-001636-3<br/>
    Cuenta cliente BN₡: 15113710010016361</p>

    <p><strong>Dólares</strong><br/>
    Cuenta Corriente BN$: 100-02-137-600935-6<br/>
    Cuenta Cliente BN$: 15113710026009357</p>
  </div>
  <div class="col-md-6">
    <h3>BAC San José</h3>
    <p><strong>Colones</strong><br/>
    Cuenta Corriente BAC₡: 924087893<br/>
    Cuenta Cliente C. BAC₡: 10200009240878934 </p>

    <p><strong>Dólares</strong><br/>
    Cuenta Corriente BAC$:  924087901 <br/>
    Cuenta Cliente C. BAC$: 10200009240879017 </p>
  </div>
  <div class="col-xs-12"
    <p>A nombre de Aidah Manaar S.A.<br/>
    Ced. Jurd.: 3-101-698973</p>
  </div>
</div>

app/views/home/contrataciones.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-offset-2">
                <div class="text-center">
                    <h2 class="center-title">Contrataciones</h2>
                    <span class="center-border-line"></span>
                    <p class="sub-text">Dale un toque único a tu evento con un espectáculo de belly dance del más alto nivel.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="contact-form wow animated fadeInLeft" data-wow-delay=".2s">
                    <form role="form" id="feedbackForm" action="https://formspree.io/info@bellydancecr.com" method="POST">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="name">Nombre *</label>
                                    <div>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Escribí tu nombre" />
                                    </div>
                                    <span class="help-block" style="display: none;">Por favor escribí tu nombre</span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="apellidos">Apellidos *</label>
                                    <div>
                                        <input type="text" class="form-control" id="apellidos" name="apellidos" placeholder="Escribí tus apellidos" />

                                    </div>
                                    <span class="help-block" style="display: none;">Por favor escribí tus apellidos</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="tel">Teléfono *</label>
                                    <div>
                                        <input type="text" class="form-control" id="tel" name="tel" placeholder="Ej: 88882323" />

                                    </div>
                                    <span class="help-block" style="display: none;">Por favor escribí tu nombre</span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="email">Correo electrónico *</label>
                                    <div>
                                        <input type="email" class="form-control" id="email" name="_replyto" placeholder="Escribí tu dirección de correo electrónico" />

                                    </div>
                                    <span class="help-block" style="display: none;">Por favor escribí una dirección de correo válida</span>
                                </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="lugar">Lugar del evento *</label>
                                    <div>
                                        <input type="email" class="form-control" id="lugar" name="lugar" placeholder="¿Dónde se llevará a cabo el evento?" />

                                    </div>
                                    <span class="help-block" style="display: none;">Por favor indicanos dónde se llevará a cabo el evento</span>
                                </div>
                            </div>
                            <div class="col-md-6">
                              <div class="form-group">
                                  <label class="control-label" for="fecha">Fecha del evento *</label>
                                  <div>
                                      <input type="email" class="form-control" id="fecha" name="fecha" placeholder="¿En qué fecha se llevará a cabo el evento?" />

                                  </div>
                                  <span class="help-block" style="display: none;">Por favor indicanos dónde se llevará a cabo el evento</span>
                              </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="hora">Hora del evento *</label>
                                    <div>
                                        <input type="email" class="form-control" id="hora" name="hora" placeholder="¿A qué hora se llevará a cabo el evento?" />

                                    </div>
                                    <span class="help-block" style="display: none;">Por favor indicanos a qué hora se llevará a cabo el evento</span>
                                </div>
                            </div>
                            <div class="col-md-6">
                              <div class="form-group">
                                <label class="control-label" for="tipo_de_actividad">Tipo de actividad *</label>
                                <div>
                                    <input type="email" class="form-control" id="tipo_de_actividad" name="tipo_de_actividad" placeholder="¿Qué tipo de actividad vas a realizar?" />

                                </div>
                                <span class="help-block" style="display: none;">Por favor indicanos para qué tipo de eventos querés contratarnos</span>
                              </div>
                            </div>
                          </div>

                        <input type="hidden" name="_subject" value="Mensaje desde la página" />
                        <input type="hidden" name="_next" value="/contrataciones/gracias" />
                        <input type="text" name="_gotcha" style="display:none" />
                        <button type="submit" id="feedbackSubmit" class="btn btn-dark-bg btn-lg" data-loading-text="Enviando..." style="display: block; margin-top: 10px;">Enviar</button>
                    </form>
                </div><!--contact form-->
            </div><!--col-7-->
        </div><!--row-->
    </div><!--container-->
</section><!--contact section end-->

app/views/home/gracias.html.erb
<div class="text-center">
  <h1>Gracias por tu mensaje</h1>
  <p>Nos pondremos en contacto lo antes posible</p>
</div>

app/views/home/import.html.erb
Import is finished!

<br>
<br>

<strong><%= l(Time.now) %></strong>

app/views/home/index.html.erb
<% content_for :body_class, "home" %>
<% content_for :banner do %>
  <%= render 'application/banner' %>
<% end %>
<% content_for :full_width do %>
  <%= render 'application/welcome' %>
  <%= render 'application/cta2' %>
  <%= render 'application/about' %>
  <%= render 'application/cta1' %>
  <%= render 'application/contact' %>
  <%= render 'application/cta_contrataciones' %>
<% end %>

app/views/home/prices.html.erb
<% first_amateur = true %>

<h2>Cursos de baile</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Lecciones por semana</th>
      <th>Precio</th>
      <th class="price-column">Precio con descuento</th>
      <th>Matrícula</th>
      <th>Nivelación</th>
    </tr>
  </thead>
  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <% if 'Amateur' == plan.name %>
          <% if first_amateur %>
            <th rowspan="<%= DancePlan.where(name: 'Amateur').count %>">
              <%= plan.name %>
            </th>
            <% first_amateur = false %>
          <% end %>
        <% else %>
          <th><%= plan.name %></th>
        <% end %>
        <td><%= plan.lessons_per_week || 'Ilimitado' %></td>
        <td><%= number_to_currency(plan.price) %></td>
        <td class="price-column"><%= number_to_currency(plan.price_with_discount) || 'N/A' %></td>
        <td><%= number_to_currency(plan.tuition) %></td>
        <td><%= number_to_currency(plan.leveling) || 'Gratis' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Otros cursos</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Precio por lección</th>
    </tr>
  </thead>
  <tbody>
    <% OtherPlan.all.each do |plan| %>
      <tr>
        <th><%= plan.name %></th>
        <td><%= number_to_currency(plan.price_per_lesson) %></td>
      </tr>
    <% end %>
  </tbody>
</table>